// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/bodokaiser/entgo-migrate-diff/ent/runtime.go

const (
	Version = "v0.11.5-0.20221109185045-b86bc12db9f7"           // Version of ent codegen.
	Sum     = "h1:a/RzWoJWjOFlStKGsB6x3c4ELGE5VOI5qIztXQInV7E=" // Sum of ent codegen.
)
